using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
    public class Category
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int categoryId { get; set; } //generated by system


        [Required]
        [MaxLength(100)]
        public string categoryName { get; set; } // user input

       
        [MaxLength(500)]
        public string? description { get; set; } // user input

        [MaxLength(300)]
        public string? imageUrl { get; set; } // user input


        //Reationship with Product (one-many)
        public List<Product> products { get; set; }

    }
}
