using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class Order
    {
        public int orderId { get; set; } //generated by system
        public int userId { get; set; } //generated bu system (user input after print from system)
        public DateTime orderDate { get; set; } //generated by system
        public decimal totalAmount { get; set; } //calculated
        public string status { get; set; } = "Pending";// Default value
        public string shippingAddress { get; set; } //user input
        public string paymentMethod { get; set; } //user input

    }
}
