using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int orderId { get; set; } //generated by system


        [ForeignKey("User")]
        [Required]
        public int userId { get; set; } //generated by system (user input after print from system)


        [Required]
        public DateTime orderDate { get; set; } //generated by system


        [Required]
        [Range(typeof(decimal), "0", "79228162514264337593543950335")] // this answer i git it from AI
        public decimal totalAmount { get; set; } //calculated
        public string status { get; set; } = "Pending";// Default value
        public string shippingAddress { get; set; } //user input
        public string paymentMethod { get; set; } //user input

    }
}
