using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class OrderDetail
    {
        [Required]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OrderDetailID { get; set; } //generated by system

        [Required]
        [ForeignKey("Order")]
        public int orderId { get; set; }  //generated by system (user input after print from system)

        
        [Required]
        [ForeignKey("Product")]
        public int productId { get; set; }  //generated by system (user input after print from system)


        [Required]
        [Range(1,1999)]
        public int Quantity { get; set; } //calculated


        //Reationship with Product (many-one)
        public Product products { get; set; }


        //Reationship with Order (many-one)
        public Order orders { get; set; }
    }
}
