using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int orderId { get; set; } //generated by system


        [ForeignKey("User")]
        [Required]
        public int userId { get; set; } //generated by system (user input after print from system)


        [Required]
        public DateTime orderDate { get; set; } //generated by system


        [Required]
        [Range(typeof(decimal), "0", "79228162514264337593543950335")] // this answer i git it from AI
        public decimal totalAmount { get; set; } //calculated


        [Required]
        [MaxLength(30))]
        public string status { get; set; } = "Pending";// Default value


        [Required]
        [MaxLength(300)]
        public string shippingAddress { get; set; } //user input


        [Required]
        [MaxLength(50)]
        public string paymentMethod { get; set; } //user input


        //Reationship with Product (many-one)
        public List<Product> products { get; set; }

        //Reationship with User (many-one)
        public User user { get; set; }

        //Reationship with OrderDetail (one-many)
        public List<OrderDetail> orderDetails { get; set; }

    }
}
