using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int productId { get; set; } //generated by system


        [Required]
        [MaxLength(150)]
        public string productName { get; set; } // user input


        [MaxLength(1000)]
        public string? description { get; set; } // user input


        [Required]
        [Range(typeof(decimal), "0", "79228162514264337593543950335")] // this answer i git it from AI
        public decimal price { get; set; } //calculated

        [Required]
        [Range(0,int.MaxValue)]
        public int stockQuantity { get; set; } //calculated



        [MaxLength(300)]
        public string? imageUrl { get; set; } //user input


        [ForeignKey("Category")]
        [Required]
        public int categoryId { get; set; } //Foreign Key from Category table



        [Required]
        public DateTime createdAt { get; set; } //generated by system
        
        
        public bool isAvailable { get; set; } = true; //Default  value

        //Reationship with Order (many-many)
        public List<Order> contains { get; set; }

        //Reationship with Review (one-many)
        public List<Review> reviews { get; set; }

        //Reationship with Category (many-one)
        public Category category { get; set; }

        //Reationship with OrderDetail (one-many)
        public List<OrderDetail> orderDetails { get; set; }




    }
}
