using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class Review
    {

        public int reviewId { get; set; } //generated by system
        public int userId { get; set; } //Foreign Key--> generated by system(user input after printed from system
        public int productId { get; set; }//Foreign Key--> generated by system(user input after printed from system
        public int rating { get; set; } //user input
        public string comment { get; set; } //user input
        public DateTime reviewDate { get; set; } //user input
    }
}
