using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class Review
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int reviewId { get; set; } //generated by system


        [ForeignKey("User")]
        [Required]
        public int userId { get; set; } //Foreign Key--> generated by system(user input after printed from system


        [ForeignKey("Product")]
        [Required]
        public int productId { get; set; }//Foreign Key--> generated by system(user input after printed from system


        [Required]
        [Range(1,5)]
        public int rating { get; set; } //user input

        [MaxLength(1000)]
        public string? comment { get; set; } //user input

        [Required]
        public DateTime reviewDate { get; set; } //user input

        //Reationship with User (many-one)
        public User user { get; set; }

        //Reationship with product (many-one)
        public Product product { get; set; }


    }
}
