using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace E_Commerce_System.Models
{
   public class User
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int userId { get; set; } //generated by system


        [Required]
        [MaxLength(50)]
        public String username { get; set; } // user input



        [Required]
        [MaxLength(150)]
        public String email { get; set; } // user input


        [Required]
        [MaxLength(250)]
        public String passwordHash { get; set; } // user input



        [Required]
        [MaxLength(100)]
        public String fullName { get; set; } // user input



        [MaxLength(20)]
        public String? phoneNumber { get; set; } // user input


        [MaxLength(300)]
        public String? address { get; set; } // user input


        [Required]
        public DateTime registrationDate { get; set; } // user input


        public bool isActive { get; set; } = true; // Default value


        //Reationship with Order (one-many)
        public List<Order> Places { get; set; }

        //Reationship with Review (one-many)
        public List<Review> Writes { get; set; }

    }
}
